### ISSUE TITLE
Establish Support Guide

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#13]
How many releases are we supporting?  Will we branch older versions of BigBang that we support but upstream does not?

e.g. if there's a critical security bug in istio, will we backport the fix to older versions of BigBang instead of just n-1?

**Comment by MxNxPx** [comment]
perhaps also...
* supported k8s versions
* environments it has been "certified on" or at least "tested on"
* roadmap for status of what is being worked for each release
