### ISSUE TITLE
DUBBD - Bastion Roles/Policies

### ISSUE THREAD

**Issue by cmharden** [defenseunicorns/uds-package-dubbd#132]
Feedback from initial DUBBD deployment:

We need to provide proper permissions that are required for Zarf to run properly on a bastion box
* We shouldn't assume that the bastion roles will be adequate

The bastion role used for their implementation were pulled from the IAC repo
* These rules in the policy had to be removed
  * "s3:PutBucketPublicAccessBlock",
  * "s3:PutAccountPublicAccessBlock"

cc: @brianrexrode

**Comment by brianrexrode** [comment]
I created this [PR](https://github.com/defenseunicorns/terraform-aws-uds-bastion/pull/32) to remove this blocker when deploying aws-dubbd pkgs

**Comment by brianrexrode** [comment]
PR was merged to main, please consider this issue closed

**Comment by MxNxPx** [comment]
closing per @brianrexrode 's comment
