### ISSUE TITLE
DUBBD - Create deployment validation

### ISSUE THREAD

**Issue by cmharden** [defenseunicorns/uds-package-dubbd#135]
Verifying platform is up and ready
* e2e testing that everything is running properly
* Run health checks
  * Are all probes setup and responding 
* Manually hit url's to validate app is running
  * services up and responding
* Backups are up and confirmed

**Comment by MxNxPx** [comment]
Using https://github.com/defenseunicorns/uds-package-dubbd/pull/270 as an example, implement testing of the core DUBBD functionality for CI validation and optional deploy time validation.
