### ISSUE TITLE
DUBBD - determine initial list of zarf variables needed

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/uds-package-dubbd#136]

**Comment by cmharden** [comment]
Currently it's only the certs and domain name
Working on more delivery interviews to flesh out the list, but delivery needs to spend more time using the package in order for us to nail down what vars are meaningful

**Comment by UncleGedd** [comment]
As part of this ticket, create documentation in the zarf-package-big-bang repo describing what variables users can change

**Comment by UncleGedd** [comment]
https://github.com/defenseunicorns/uds-package-dubbd/pull/273
