### ISSUE TITLE
Increase number of concurrent CI Jobs

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#138]
We're limited to 5 VPCs in our testing account.  to increase our ability to run more jobs we should increase the number that we're allowed to create. Another option would be to re-use one vpc for all the clusters, but when switching to #116 or lower parts of the stack, we might be forced to create VPCs anyways so would need to increase this regardless

**Comment by oates** [comment]
@Vandiver247 will you be able to put in the request for the increase to AWS through the support portal? @runyontr should this be done in our new Product account we are creating now as well?

**Comment by runyontr** [comment]
And our testing account
