### ISSUE TITLE
Test Updates of BB Versions for DUBBD

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#14]
For testing we should be sure we can rollback on failures

Deploy 1.52
Deploy 1.53
Rollback to 1.52

**Comment by cmharden** [comment]
Test upgrade of dubbd with a failed state
* document behavior
* Expected state: Flux is still working and zarf just shows failed to deploy

Decision?
What should the rollback proc be for now?
* Redeploy of the previous version?
* Zarf needs to handle(on deploy fail action?)
* Some other option?

**Comment by mjnagel** [comment]
Big piece of nailing this down is having zarf properly catch errors so that we can use `onFailure` actions. https://github.com/defenseunicorns/zarf-package-big-bang/pull/188 puts *part* of that into place by triggering reconciliation of all packages on updates, and waiting on the Big Bang gitrepo/helmrelease to update to the version of BB expected. This works well for upgrades that include a BB version update but does not necessarily account for other scenarios perfectly. 

We may want to consider pulling in the `flux` CLI to directly trigger a `flux reconcile hr bigbang -n bigbang --with-source` rather than approaching with annotations and homegrown waits.

**Comment by mjnagel** [comment]
https://github.com/defenseunicorns/zarf-package-big-bang/pull/195 is a second small piece, "fully rollback" (aka uninstall) when an installation (non-upgrade) fails to deploy. This is the simpler scenario where we can delete all of DUBBD. One decision point - do we leave Flux always, delete it always, or try to determine if Flux "pre-existed" and handle uniquely based off of that? DUBBD itself assumes we are deploying Flux (not pre-existing) so I lean towards delete always, but not sure if that hinders extensibility.

**Comment by mjnagel** [comment]
> We may want to consider pulling in the `flux` CLI to directly trigger a `flux reconcile hr bigbang -n bigbang --with-source` rather than approaching with annotations and homegrown waits.

Tested this yesterday and the `flux` CLI brings a lot of benefits - it has caught 100% of failures in my tests so far and is still relatively small to pull in the binaries. In combo with the checksums on all HRs (coming in BB 2.3.0 hopefully - https://repo1.dso.mil/big-bang/bigbang/-/commit/f3adb3ca06c8324f6632594f461f610e5f61ac89) upgrades should be triggered close to instantly after `zarf package deploy` which should ensure that the `onDeploy.after` waits will catch the state post-upgrade.

**Comment by mjnagel** [comment]
Worked with @MxNxPx and we identified a few different options for how to handle upgrade failures/rollbacks:
- As-is: Currently DUBBD will catch/report failures and leave all failure handling to Flux. Flux will do 3 retries per helmrelease (neuvector, kyverno, etc) and then do a rollback to the previous version for that specific helmrelease only.
- DIY Rollback
  1. DUBBD's values for flux would configure 0 retries and no remediation strategy
  2. On failure zarf will report there was a timeout on a certain package/helmrelease, but cluster will be left in a "broken state"
  3. There is no auto-rollback, leaving users with 2 options:
      a. Run a zarf deploy with the previous version of the package (this would effectively be a manual rollback)
      b. Identify and fix the issue that caused the failure (values, cluster state, etc?) then build a new package if needed and deploy (edited) 
- Full Rollback
  1. DUBBD determines it is performing an upgrade via preflight check and below logic is conditionally triggered
  2. Zarf action for before deploy in DUBBD would be to backup secrets
    a. Get a list of all the BB valuesFrom secrets that DUBBD previously deployed (using a unique label in the zarf ns <-- requires a zarf change to the extension)
    b. Using sed or some other method, add/update a backup label & give the secrets a prefix or suffix to indicate it is a backup
    c. Do something similar with the package zarf secret for DUBBD
  3. If the DUBBD deploy (preflight check determined upgrade=true) fails, initiate a rollback via onfailure action
    a. Take the backup BB valuesFrom secrets and apply them over the existing secrets
    b. Patch the zarf extension BB umbrella helm release and reconcile
    c. Return the previous package zarf secret for DUBBD
- Hybrid Approach: Likely a combination of the DIY and full rollback approaches, but with a zarf variable to toggle between options to allow flexibility based on the use case.

**Comment by UncleGedd** [comment]
As part of this ticket, document the supported upgrade path for the DUBBD-AWS package. For example, are users able to skip package versions or not.

**Comment by mjnagel** [comment]
This is largely complete except the documentation of supported upgrade paths. We will also need a follow on issue for the "full rollback" approach as an option - in the current state flux is configured with no retries or rollbacks.

**Comment by UncleGedd** [comment]
For 16 June, we will NOT be considering rollback functionality

**Comment by UncleGedd** [comment]
@MxNxPx and @mjnagel are working on docs for the upgrade path

**Comment by austenbryan** [comment]
FYSA - I updated the title of this issue based on slack comms and the above.

Linking roll back portion of the issue separately tracked now https://github.com/defenseunicorns/uds-package-dubbd/issues/269
