### ISSUE TITLE
CoCoWoW - Research Spike to add a mission app to an existing cluster

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/uds-package-dubbd#141]
This is a research spike to determine if deployment of a mission app can be done separately from the deployment of Big Bang (CoCoWoW), or if we are required to integrate the mission app into the same zarf package that deploys Big Bang (CoCoWoW)

Success Criteria: I'm able to deploy Big Bang + Keycloak + Authservice using the CoCoWoW Zarf Package, and then I can deploy the mission app on top of it, and still meet all of the criteria in #140

Failure Criteria: I was not able to determine how to deploy the mission app separately. The only way to meet all of the criteria in #140 was to deploy Big Bang + Keycloak + Authservice + Mission App as one unit.

**Comment by RothAndrew** [comment]
This is blocked until we have a viable zarf package of Big Bang + Keycloak + Authservice (a.k.a. CoCoWoW). Until we have that, we don't really have the ability to make this determination.
