### ISSUE TITLE
Enable Velero for cluster backups

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#19]
also need to co-configure backups for all the pieces:

Estabish backup processes and documentation:

- [ ] cluster
- [ ] Loki log data when stored in a PVC.  Velero doesn't backup s3
- [ ] prometheus monitoring data
- [ ] grafana pvc
- [ ] neuvector data?

**Comment by oates** [comment]
closing as old issue - three amigo meeting
