### ISSUE TITLE
DUBBD - If metricsServer is deployed it is not verified like all other helmReleases

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-package-dubbd#203]
Pretty much as the title says. While testing kind the metricsServer failed but the package said it deployed successfully. If we're gonna check everything else we should check the metricsServer too.

**Comment by MxNxPx** [comment]
closing as this (at least now) does get validated via a zarf wait command (see related issue [here](https://github.com/defenseunicorns/zarf/issues/2054))
