### ISSUE TITLE
Spike on UDS Testing Framework

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#213]
As a UDS dev
I want to identify and decide on a testing framework for testing UDS packages
So that developers can have confidence that their code works as intended

**Acceptance Criteria**
- Test and document some testing frameworks for writing tests for UDS packages (ie. Terratest, Robot Framework, etc.)
- Discuss with team
- Write an ADR to record why the team chose a specific framework

**Comment by austenbryan** [comment]
Thanks for kicking this off @UncleGedd . Just had a similar convo with @zachariahmiller this morning
