### ISSUE TITLE
Dogfood DUBBD-AWS package *needs grooming*

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#214]
As a UDS dev
I want to run and utilize a long-lived DUBBD-AWS package
So that I can get insights into how a DUBBD-AWS package runs in prod

In Philly we discussed the idea of starting with Github Actions Runners in the short term. However, I believe this assumes that we need a Github Actions Runner package to run on top of DUBBD. Need to hash out these details

**Comment by wirewc** [comment]
Touch point, the work done [here](https://github.com/defenseunicorns/uds-aws-ci-k3d) is in effort to move on this issue.

**Comment by MxNxPx** [comment]
closing this as the work to dogfood is now a full (separate) initiative
