### ISSUE TITLE
Create a faster feedback loop for DUBBD in CI

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#216]
As a UDS dev
I want a more lightweight cluster for DUBBD in CI
So that I don't have to wait for EKS clusters to be created/destroyed
```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-package-dubbd/issues/337
```

**Comment by zachariahmiller** [comment]
I have a PR into the branch lucas is working on integrating with renovate https://github.com/defenseunicorns/uds-aws-ci-k3d/pull/8

Once those are both merged in we can cut a tag and begin on the PR into the dubbd repo.

**Comment by UncleGedd** [comment]
Completed
