### ISSUE TITLE
ADR For Exposing Apps

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#218]
As a UDS dev
I want to know what apps are behind which Istio IngressGateway
So that I can document what apps are and are not exposed to UDS users

Create a small ADR to document why particular apps are behind a particular Istio IngressGateway

**Comment by oates** [comment]
related to #29

**Comment by MxNxPx** [comment]
PR created: https://github.com/defenseunicorns/uds/pull/150
