### ISSUE TITLE
Enable tetrate istio distribution

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/uds-package-dubbd#221]
As a user required to meet fips compliance, I need the ability to utilize the tetrate istio distribution in DUBBD. I can currently override these values in my zarf package but would like this feature to be supported.

**Comment by zachariahmiller** [comment]
picking up this late requirement for release next week. Appreciate Gabe raising this up, but as a product team we need to get better at identifying things like this earlier.

**Comment by mjnagel** [comment]
```yaml
istio:
  enterprise: true
```
https://repo1.dso.mil/big-bang/bigbang/-/blob/master/chart/values.yaml#L171-173

This should be a quick change to make, but pending the discussion around whether this should be set by default and/or exposed as a zarf var.

**Comment by zachariahmiller** [comment]
waiting for decision from @austenbryan before implementing this.

**Comment by austenbryan** [comment]
Recommend we use Tetrate's Istio distro @zachariahmiller and that we remove this issue as being blocked.

Rationale from Tetrate PM on contract with Platform One

"Yes it does include keeping them updated.
Our renewals occur yearly with them in the March - April timeframe. We’re currently on year 3. Next renewal will be year 4. We’re not worried about them not renewing. But even if that’s ever the case. It’s in our best interest to continue to keep the images in iron bank up to date. Hope this helps.""
