### ISSUE TITLE
Don't download extra flux "packages"

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-package-dubbd#255]
on `zarf package create`
https://github.com/defenseunicorns/uds-package-dubbd/blob/12d61ba67f6aa5ca5b3396b54b68c946b1e91a6c/defense-unicorns-distro/zarf.yaml#L109 downloads flux

I know my target environment and don't want extra bytes in my zarf package.

Possibly add variables to include OS and architecture. It seems the extract_flux.sh script already has support.

`- cmd: "./extract_flux.sh ###ZARF_PKG_TMPL_FLUX_VERSION###"`

**Comment by mjnagel** [comment]
Wanted to save off an idea that @MxNxPx had for things like this - potentially we could run the flux commands in cluster (in an k8s job?) which would get rid of the architecture issue although it may add more complexity with manifests necessary for the job, role, rolebinding, etc, etc.
