### ISSUE TITLE
Determine the controls in place

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/uds-package-dubbd#27]
will we be relying on BB for defining and mapping controls implemented?

**Comment by runyontr** [comment]
While there are some controls specified by BigBang for each package, we need to look through those controls, identify how they are implemented, verify they are actually implemented in this distro and provide that documentation here in the repo:

e.g. https://repo1.dso.mil/big-bang/product/packages/istio-controlplane/-/blob/main/oscal-component.yaml

AC-3: Based on the description there, if there isn't a global `RequestAuthentication` policy that's created for ensuring all ingress access has a particular JWT token, it doesn't seem like the control is actually going to be satisfied.  So we need to ensure that we're either making it, or satisfying that for applications running on top in particular ways.
