### ISSUE TITLE
Refactor IaC in Zarf pkg and add tests

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#277]
Currently, whenever we test IaC specific things in DUBBD-AWS, we have to spin up an entire EKS cluster which creates a long feedback loop for devs. This issue to migrate some of the IaC-specific components out of the main DUBBD-AWS `zarf.yaml` and into the `aws/loki` folder, as well as, write a "unit" test for IaC-specific components

**Comment by UncleGedd** [comment]
Blocked for now until we decouple S3 and IRSA, need to create an IRSA TF module

**Comment by wirewc** [comment]
@UncleGedd proposed solution for decoupling S3 and IRSA in a single repository. 

If we move all the IRSA functionality into a submodule in the same repository, we may get the modular like behavior that is desired.  

Presently, the attempt perform a dual purpose (IRSA and non-IRSA) behavior will fail as Terraform will always need the IRSA variables to be populated even if they are not used. If a submodule is used, the variables should be able to be safely ignored.

**Comment by austenbryan** [comment]
No longer in scope given UDS CLI and IaC Tool work
