### ISSUE TITLE
Create ADR for Autoscaler

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#294]

**Comment by mjnagel** [comment]
For HA/HPA type things Big Bang has documented HA requirements for most packages under the subpages on https://docs-bigbang.dso.mil/latest/docs/understanding-bigbang/package-architecture/

Example for Kiali: https://docs-bigbang.dso.mil/latest/docs/understanding-bigbang/package-architecture/kiali/#High-Availability
