### ISSUE TITLE
Support and Test Airgap

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#296]
As a product engineer
I want to ensure UDS packages can be run in an egress-restricted environment

### Notes
- Maybe we can test UDS packages in an env that doesn't have access to the internet (maybe through SecurityGroups?)

**Comment by mjnagel** [comment]
@wirewc is this one being worked currently? Not trying to pick it up, just wanted to make sure it didn't get accidentally moved around on the board.

**Comment by wirewc** [comment]
It was accidentally moved around on the board @mjnagel. What happened was I tried to move the EKS module to review on my phone. Do not use the phone app for moving issues on the board.
