### ISSUE TITLE
Create explicit Kubernetes Requirements Guide

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#30]
Based on our configuration we should be able to explicitly state what's needed to run the cluster:

1. StorageClass (and PVC sizes)
2. CPUs
3. Memory
4. Nodes
5. Kubernetes Versions
6. zarf init with the git server

We should make it very clear what's needed and maybe even put a preDeploy check to validate any of the requirements using zarf actions

**Comment by cmharden** [comment]
Initial feedback from @brianrexrode 
3 - m5-xlarge nodes are not enough to run DUBBD
6 or 7 - m5-xlarge or 3 m5-2xlarge seem to be big enough for a base DUBBUD implementation without application workloads
