### ISSUE TITLE
Secure default authentication/credentials

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-package-dubbd#304]
Currently DUBBD does no configuration for default credentials/authentication. Grafana and NeuVector are configured with default admin user/pass configs that would be insecure in a production environment. 

We have a number of different options for how to handle this:
- Require user to pass in zarf vars to configure user/pass for default admin
- Randomly set a user/pass for default admin (and add to secret somewhere?)
- Disable default admin (is this possible?)
- Document a post-install step for user to setup/change default credentials

**Comment by noahpb** [comment]
Added auto-generation of default creds for grafana in https://github.com/defenseunicorns/uds-package-dubbd/commit/b4ec6a71eda00a5e373a8a34d13e916d3954e549
