### ISSUE TITLE
First Blog Post

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#32]
We should look at what the first great blog post would be to show someone easily deploying BigBang with this package

1. What Kubernetes clusteR?
2. what do they provide for deploy time variables?
3. what do they get to do after they deploy it?

cc @austenbryan

**Comment by MxNxPx** [comment]
done thanks to @laurenmengert !!!
https://medium.com/defense-unicorns/defense-unicorns-big-bang-distribution-1276e6309718
