### ISSUE TITLE
Refactor the UDS S3 module to use common workflows

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#323]
As a UDS dev
I want the UDS S3 Terraform module to use common workflows
So that we don't have duplicated code in that module

**Comment by wirewc** [comment]
Linking previous PR that was used for testing. This issue will be notified and the PR will be pulled out of draft mode when ready.

**Comment by wirewc** [comment]
Working on fixing `go test` for the Terraform Test functionality. Right now, logging messages are not showing up until after the test has completed in it's entirety. This is not good for monitoring and testing any Terraform. The issues are compounded by longer running modules (such as EKS). 

After speaking with @UncleGedd, I will spend a time boxed amount of time to address this issue and will record my findings for best practices.

**Comment by wirewc** [comment]
After working with @zachariahmiller and refactoring a test to see the root cause of the lack of streaming logs. 

It looks like there is an open issue with go on streaming logs when run in parallel [here](https://github.com/golang/go/issues/46959). 

The solution that should be added to the go test common workflow is:
```bash
go test ./... -count 1 -p 1 -v
```

**Comment by wirewc** [comment]
An issue was created based on work for the previous comment in the UDS Common Workflow here: https://github.com/defenseunicorns/uds-common-workflows/issues/48

**Comment by wirewc** [comment]
With the help of @RothAndrew, a solution was found that preserves the parallel testing with the immediate logging.

**Comment by wirewc** [comment]
Common workflow has been added and awaiting review.
