### ISSUE TITLE
Refactor the UDS KMS module to use common workflows

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#324]
As a UDS dev
I want the UDS KMS Terraform module to use common workflows
So that we don't have duplicated code in that module

**Comment by wirewc** [comment]
After review of https://github.com/defenseunicorns/uds-package-dubbd/issues/323, the same principles were applied to this repository and are ready to be close.

**Comment by wirewc** [comment]
Attached Pull request is ready to be reviewed.
