### ISSUE TITLE
Refactor the UDS RDS module to use common workflows

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#325]
As a UDS dev
I want the UDS RDS Terraform module to use common workflows
So that we don't have duplicated code in that module

**Comment by wirewc** [comment]
Shared workflows are migrated. However, testing looks like one the tests cannot complete before some 10 minute timeout. Presently investigating how to expand the time out time.

**Comment by wirewc** [comment]
The timeout issue was resolved https://github.com/defenseunicorns/uds-common-workflows/pull/53. Work will resume after the pull request has been accepted.
