### ISSUE TITLE
Create DNS Records when DUBBD is deployed on AWS

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#332]
As a delivery engineer
When I deploy DUBBD-AWS or UDS Core AWS
I want Route53 entries created and pointed to the Istio load balancers
So that I don't have to manually configure routes in AWS

### Notes
- Assume a hosted zone has already been created and we can ingest the config(s) for it
- If this ticket is too big we can split into 1) create Route53 entries and 2) point Route53 entries at Istio LBs, but they can't be done in parallel

**Comment by justin-o12** [comment]
Also, can we see an example record?

**Comment by MxNxPx** [comment]
It would be helpful to me to decide on how we would prefer to approach this problem with regards to:
1. whether this should be part of dubbd-aws or part of uds-core-aws
1. if it is preferred to handle this via terraform or some other option (for example: using [external-dns](https://github.com/kubernetes-sigs/external-dns) in the cluster)

i am currently leaning towards uds-core-aws along with external-dns (with some prereqs)...

what are you thoughts @UncleGedd and others?

**Comment by justin-o12** [comment]
Just providing more information:  [current implementation in Terraform](https://github.com/defenseunicorns/terraform-aws-workspaces/blob/main/main.tf).

**Comment by UncleGedd** [comment]
@MxNxPx good questions, this would be part of both dubbd-aws and uds-core-aws. Personally, I'd start with ExternalDNS and see if it's a viable option

**Comment by MxNxPx** [comment]
Draft PR created: https://github.com/defenseunicorns/uds-package-dubbd/pull/346

**Comment by MxNxPx** [comment]
Still need to add terraform to create a policy and irsa to pass into the external-dns helm chart, then it should be ready for review.

**Comment by MxNxPx** [comment]
need to decide for CI  if we want to:
1. create a long-lived shared route53 private hosted dns zone, and have each eks cluster VPCs added and removed (potential conflict with DNS records across multiple clusters)
1. create a long-lived shared route53 private hosted dns zone, but tie some long-lived VPC to it and don't add and remove the eks cluster VPCs
1. feed it bogus route53 zone and not worry about the errors in the external-dns logs

**Comment by MxNxPx** [comment]
found out that passing the route53 hosted dns zone is not a requirement (it will look for a zone that matches the domain used) and even if a matching zone does not exist, the helm install is still successful.  so CI will follow the path of not utilizing a hosted dns zone which will also help avoid potential conflicts across multiple clusters trying to manage records in a shared zone.

**Comment by MxNxPx** [comment]
addressed via https://github.com/defenseunicorns/uds-package-dubbd/pull/346
