### ISSUE TITLE
Refactor loki and velero s3 bucket deploy logic

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-dubbd#354]
As a product engineer I want to be able to have less code duplication for repetitive tasks in the zarf yaml as code duplication makes it harder to add new functionality as well make updates to existing functionality in the zarf.yaml. 

Currently there are two identical steps except for a single name string for the s3 bucket, kms, irsa step of the aws-dunbd package (for loki and velero). This is a good candidate for refactorong the duplicate code to at least abstract away some of the inline terraform shell scripting.

**Comment by zachariahmiller** [comment]
@UncleGedd here is the ticket you asked for the work @wirewc and I were working on to support @cmharden's work with velero.

IMO it might be possible to get some good abstraction from what I was putting in place. A better spot for that pattern is probably the download/setup terraform step being moved into its own component, but it was still a lot of boilerplate around the variables and nesting components to get it working (which it's still failing on the long pipeline 😣).

Unfortunately, we had to rely on incidental functionality relating to component ordering. Anyways as an alternative to the approach I went down I was thinking **_If_** you did want loki and velero s3 provisioned via the same terraform but able to be deployed/destroyed independently the resource targeting could be used like: terraform apply -target=module.s3-loki

Either way I think it makes sense to put limited effort into the how on this process until we have had time to evaluate other ways of deploying/managing IaC resources.

**Comment by UncleGedd** [comment]
> Either way I think it makes sense to put limited effort into the how on this process until we have had time to evaluate other ways of deploying/managing IaC resources.

100%, I'm good with calling it a spike and capturing lessons learned to inform how we might handle IaC outside of Zarf
