### ISSUE TITLE
Update workflows so that required jobs "run" always

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-package-dubbd#381]
On certain PRs no workflows (or only some workflows) will run due to the `paths` and `paths-ignore` settings.

This repo requires certain workflows to run and pass on all PRs, however, which means that certain PRs cannot be merged without overriding the rules. We should find a solution for this.

Possible paths to explore:
- Remove the workflows as required - this is probably worst case
- Modify workflows to run a check for changes to specific files. This would mean removing the paths/paths-ignore and running workflows always, but the workflows would quickly exit if there are no changes to specific files.
- Run workflows based on command/comment? `/test all`, etc.

**Comment by MxNxPx** [comment]
For example: when release-please cuts a release, it doesn't trigger any workflow runs (because GH bot commits don't trigger workflow).  I like the idea of being able to trigger workflow runs with a PR command/comment.
