### ISSUE TITLE
ensure dubbd-aws s3 bucket creation is compatible with typical aws policies

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/uds-package-dubbd#394]
as a platform engineer deploying dubbd aws, i would want the s3 buckets to be created in a way that is compatible with policies already in place.

**Comment by MxNxPx** [comment]
linking this ticket: https://github.com/defenseunicorns/terraform-aws-uds-bastion/pull/32

**Comment by MxNxPx** [comment]
@brianrexrode confirmed that a recent dubbd-aws install from the bastion required tweaking the bastion policy to work.

**Comment by MxNxPx** [comment]
noticed https://github.com/defenseunicorns/terraform-aws-uds-bastion/pull/32 was merged yesterday.  would like to confirm if we can consider this issue closed as a result.

**Comment by brianrexrode** [comment]
yeah, we just need to cut a new tag but consider it closed

**Comment by MxNxPx** [comment]
closing per @brianrexrode's comment
