### ISSUE TITLE
Use Existing K3d Local Setup in CI

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#406]
As a product engineer
I want to use the same k3d setup in DUBBD and in CI
So that we can dogfood the k3d setup that we publish on Github

**Comment by zachariahmiller** [comment]
replaces: https://github.com/defenseunicorns/uds-aws-ci-k3d/issues/4 and https://github.com/defenseunicorns/uds-aws-ci-k3d/issues/6

Additionally, as part of this refactor may take care of https://github.com/defenseunicorns/uds-aws-ci-k3d/issues/20 or may complete it after in it current form

**Comment by TristanHoladay** [comment]
now using uds-k3d in CI.
