### ISSUE TITLE
Add UDS Pepr Controller to DUBBD

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#409]
As a UDS package dev
I want to deploy the UDS Pepr Controller
So that I can automate post-installation steps

https://github.com/defenseunicorns/uds-pepr-controller

**Comment by UncleGedd** [comment]
Blocked until we figure out to "bundle" multiple Pepr modules into the same UDS package

**Comment by UncleGedd** [comment]
https://github.com/defenseunicorns/uds-pepr-controller

**Comment by TristanHoladay** [comment]
Closing because efforts are now focused on UDS-Core which uses Pepr.
