### ISSUE TITLE
Ensure We Aren't Creating Resources in non-US AWS Regions

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#413]
Ensure that none of our tests (especially the S3 module) are creating resources outside US regions.

Note:  Not modifying the tests in the VPC module as this work will also remove the dependency on the UDS VPC module from the RDS module.

```[tasklist]
### Packages
- [x] S3 module
- [x] KMS module
- [x] IRSA module
- [x] RDS module
```

**Comment by zachariahmiller** [comment]
IMO we really ought to support testing in more than just west (for example the iac modules test in multiple east regions). Agree with the title of the ticket, but think the description should probably be that we aren't creating resources out of the us regions.

**Comment by justin-o12** [comment]
@UncleGedd, did you have an example of a resource or test running in a non-US region?

**Comment by zachariahmiller** [comment]
#2 and if that's not enough then we find a way to alert and/or remediate resources created in regions we don't want/expect

**Comment by justin-o12** [comment]
PR for S3 module:  https://github.com/defenseunicorns/terraform-aws-uds-s3/pull/23

**Comment by justin-o12** [comment]
PR for KMS module: https://github.com/defenseunicorns/terraform-aws-uds-kms/pull/10/files

**Comment by justin-o12** [comment]
PR for IRSA module https://github.com/defenseunicorns/terraform-aws-uds-irsa/pull/7

**Comment by justin-o12** [comment]
PR for RDS https://github.com/defenseunicorns/terraform-aws-uds-rds/pull/30
