### ISSUE TITLE
Perform linting/scanning on terraform

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-package-dubbd#431]
The terraform in this repo has some terratests running but does not have linting or scanning being performed. We should adopt the common workflow for any tf in this repo - https://github.com/defenseunicorns/uds-common-workflows/blob/main/.github/workflows/terraform-scan.yaml

**Comment by TristanHoladay** [comment]
Is this still important now that DUBBD is decoupled from infra and the only TF is in CI?

**Comment by mjnagel** [comment]
Probably not...but it _could_ still be valuable to scan what we are running in CI? No strong opinions because I'm not sure exactly what those lint/scan steps actually check for.
