### ISSUE TITLE
ADR For Fixing Borked Releases

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/uds-package-dubbd#447]
As an engineer
&nbsp;&nbsp;&nbsp;&nbsp;My hair is on fire (or my scalp in the case of Gedd, Justin, Chase, Tommy ,etc)
&nbsp;&nbsp;&nbsp;&nbsp;Because I just realized the current release of DUBBD is broken
I want an ADR describing what we do when we find out a release is a broken
So that the team has a formal doc outlining what the prescribed remediation steps are

Noting that I'm saying ADR but this could also be a doc, don't care what we call it as long as the team knows it exists and where to find it

**Comment by mjnagel** [comment]
Would also like the team to evaluate the current testing that happens during/around the release process. I can open a separate issue for that though since it would be beyond just a doc/ADR.

**Comment by MxNxPx** [comment]
discussed with the team and planning to address this incrementally:
* short term: playbook with manual steps
* medium term: automate the manual steps
* medium-long term: address testing per @mjnagel 's comment
