### ISSUE TITLE
Errors when deploying DUBBD package

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-package-dubbd#570]
Version of DUBBD being used: v0.9.1

https://github.com/defenseunicorns/narwhal-delivery-reference-deployment/pull/11

"zarf: command not found" -- Of course it is there. It is running this deployment.

<img width="541" alt="image" src="https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/d791642a-1499-4533-934c-3873ee2a7ff0">

https://github.com/defenseunicorns/narwhal-delivery-reference-deployment/actions/runs/6240947116/job/16942143526#step:3:5838

<img width="1292" alt="image" src="https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/085422bd-57da-4123-8654-248f7bcc0e4b">

https://github.com/defenseunicorns/narwhal-delivery-reference-deployment/actions/runs/6240947116/job/16942143526#step:3:5862

**Comment by RothAndrew** [comment]
The zarf not found thing is an issue that I'm fixing in the bastion module. Still struggling with the main issue which is this "connection refused" error in the 2nd screenshot.

**Comment by corang** [comment]
Is zarf on your path?

**Comment by RothAndrew** [comment]
It wasn't, I'm fixing that. Though I don't think zarf not being in path caused the error, it just made it so that the post-error script didn't work right.

![image](https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/bf95cbd9-3524-403d-ae65-c6ec5e468563)

**Comment by RothAndrew** [comment]
The same error didn't happen on this latest run. Either something I did fixed it or it is an intermittent error. Will reopen if I see it again.
