### ISSUE TITLE
Intermittent error: "the server doesn't have a resource type 'hr'"

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-package-dubbd#603]
Getting this error intermittently when trying to deploy DUBBD. Most of the time the deployment works, sometimes it throws this error and fails:

![image](https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/b1366ac1-e2ca-41db-9664-8e27d27ecf33)

**Comment by RothAndrew** [comment]
DUBBD version we are using is v0.11.1

**Comment by mjnagel** [comment]
Do you have more details on what failed before the screenshot? That screenshot is output from the on failure script, which runs after a failure has already happened. The fact that HR isn't recognized would make me guess that the DUBBD install failed before getting to Flux but without more logs I'm not sure how to identify where the actual failure was.

**Comment by RothAndrew** [comment]
ATM no. Next time it happens I will capture more.

**Comment by RothAndrew** [comment]
![image](https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/154c0363-aac8-4bab-becc-6431b4c83170)
![image](https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/4ed62639-19be-47c1-90c4-d3dfe70ad6c6)
![image](https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/b8c49f4e-a2a7-4307-9c36-803bdb00915f)
![image](https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/fd4251eb-f455-47e9-a575-00bc6cafe376)
![image](https://github.com/defenseunicorns/uds-package-dubbd/assets/16000938/f1a8876c-883d-4cb1-9bb4-51f3bb8bb4d5)

**Comment by mjnagel** [comment]
Thanks @RothAndrew - looks like the error is actually coming when zarf is pushing images to the registry? Towards the bottom of the 3rd screenshot I see a failure during the port forward it looks like? Makes me wonder if it's less to do with DUBBD and more something with zarf or the cluster?

**Comment by mjnagel** [comment]
I think on the DUBBD side it's not a bad idea to update the on failure script so that we check for resource existence before trying to get HRs, etc. That would help provide some clarity of the real error I'd hope?

**Comment by RothAndrew** [comment]
This was with Zarf v0.30.1
