### ISSUE TITLE
Identify how to access private ELBs

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#71]
We need an easy to use way for non-technical people to access private VirtualServices

Related to #29 

* tailscale/headscale
* wireguard
* SSM
* https://github.com/slackhq/nebula
* https://www.boundaryproject.io/

**Comment by wirewc** [comment]
@oates and @UncleGedd, this issue fell off the old project board. I'm bumping this for consideration of priorities as this would be helpful in terms of DUBBD adoption.

**Comment by MxNxPx** [comment]
Handy (likely biased) comparisons:
https://tailscale.com/compare/
