### ISSUE TITLE
Setup Renovate Bot to look for new versions of Zarf in CI

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#84]
The pipelines use zarf for testing and deployment and we should be staying up to date there

**Comment by MxNxPx** [comment]
leaving these notes for reference:
although renovate [typically ootb will update github actions versions](https://docs.renovatebot.com/modules/manager/github-actions/), in this case we are not updating the action but the version of zarf the zarf-setup action uses.  so we need a custom regex manager and some comments added in the workflows for renovate to be able to do the job.

**Comment by MxNxPx** [comment]
closing as it was completed in the PR referenced in this GH issue.
