### ISSUE TITLE
Setup Re-occuring cleanup of AWS account

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#85]
Sometimes bad things happen and the aws resources don't get cleaned up.  Lets clean them up automagically:

https://github.com/defenseunicorns/zarf-package-big-bang/actions/runs/4627614569/jobs/8185734592?pr=83

**Comment by runyontr** [comment]
This was my local command:

```bash
#!/bin/bash

for stack in $(aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE ROLLBACK_COMPLETE --query 'StackSummaries[].StackName' --output text); do
  echo "Deleting stack: $stack"
  aws cloudformation delete-stack --stack-name $stack
done

```

**Comment by oates** [comment]
closing as old issue. @justin-o12 has a different issue for this he is working now.
