### ISSUE TITLE
Create Custom BB Zarf Init with Iron Bank Images

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/uds-package-dubbd#88]
A good majority of the zarf package big bang consumers may have IronBank container requirements. It may be useful to provide a tested, custom zarf init package that specifies those images. 

One downside is that there may be delays in zarf releases getting approved or some versions of apps may not be available. One the upside, we could remove PLG from the custom init package since bigbang brings logging.

v0.25.2 zarf init package images:
  - registry:2.8.1
  - ghcr.io/defenseunicorns/zarf/agent:v0.25.2
  - gitea/gitea:1.18.5

latest IB images:
  - registry1.dso.mil/ironbank/opensource/docker/registry-v2:v2.8.1
  - registry1.dso.mil/ironbank/opensource/defenseunicorns/zarf/zarf-agent:v0.25.0
  - registry1.dso.mil/ironbank/opensource/go-gitea/gitea:v1.19.0

**Comment by MxNxPx** [comment]
https://docs.zarf.dev/docs/zarf-tutorials/custom-init-packages#swapping-images

**Comment by TristanHoladay** [comment]
Still no movement on the IB image issue. But currently have this PR (https://github.com/defenseunicorns/zarf/pull/2069) waiting for final review before merging into zarf.

**Comment by TristanHoladay** [comment]
https://github.com/defenseunicorns/zarf/pull/2069 has been merged

still no update on the issue for IB gitea

**Comment by TristanHoladay** [comment]
IB gitea image updated, but there are some issues. 
1) they tagged the image as `:rootless` not `vx.x.x-rootless` -- not a problem, though, if danny gershman's PR (https://gitea.com/gitea/helm-chart/pulls/534) to gitea helm chart is accepted.
2) they only updated the latest image version (1.20.5) with the ini file fix, which does not work with the 8.3.0 helm chart currently hardcoded in the packages/gitea/zarf.yaml. So working on using latest IB gitea version with latest gitea chart version.

**Comment by TristanHoladay** [comment]
Draft Zarf PR to update Helm Chart: https://github.com/defenseunicorns/zarf/pull/2123

PR to Gitea for Decoupling Image from Rootless: https://gitea.com/gitea/helm-chart/pulls/550
